### Create User
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Naveen",
  "email": "naveen3@gmail.com",
  "password": "1234",
  "role": "USER"
}

### Register Event 1
POST http://localhost:8080/registrations
Content-Type: application/json

{
  "userId": 1,
  "eventId": 1
}

### Register Event 2
POST http://localhost:8080/registrations
Content-Type: application/json

{
  "userId": 1,
  "eventId": 2
}

###
POST http://localhost:8080/events
Content-Type: application/json

{
  "title": "Workshop",
  "description": "Tech workshop",
  "venue": "Hall 2",
  "eventDate": "2026-04-21T10:00:00",
  "maxAttendees": 50,
  "currentRegistrations": 0,
  "status": "UPCOMING"
}