spring.application.name=event-management-backend

spring.datasource.url=jdbc:mysql://localhost:3306/hr?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=bhanu2003
spring.datasource.password=Bhanu@2003
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081